//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwitchToNUnit3 {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SwitchToNUnit3.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpectedExceptionAttribute is deprecated and will be removed in NUnit3. User Asser.ShouldThrow&lt;Exception&gt; instead..
        /// </summary>
        internal static string AnalyzerDescription {
            get {
                return ResourceManager.GetString("AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throws is deprecated, catch Exception yourself is recommended..
        /// </summary>
        internal static string AnalyzerDescription2 {
            get {
                return ResourceManager.GetString("AnalyzerDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUnit3 does not support TestCaseSource that are instance members..
        /// </summary>
        internal static string AnalyzerDescription3 {
            get {
                return ResourceManager.GetString("AnalyzerDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUnit3 does not allow async void test methods, use async Task instead. .
        /// </summary>
        internal static string AnalyzerDescription4 {
            get {
                return ResourceManager.GetString("AnalyzerDescription4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpectedExceptionAttribute is deprecated.
        /// </summary>
        internal static string AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throws is deprecated.
        /// </summary>
        internal static string AnalyzerMessageFormat2 {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referenced TestCaseSource has to be static.
        /// </summary>
        internal static string AnalyzerMessageFormat3 {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormat3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Async void is not allowed. use async Task instead..
        /// </summary>
        internal static string AnalyzerMessageFormat4 {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormat4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deprecated.
        /// </summary>
        internal static string AnalyzerTitle {
            get {
                return ResourceManager.GetString("AnalyzerTitle", resourceCulture);
            }
        }
    }
}
